import "@/styles/globals.css";
import { Container, Flex, Theme } from "@radix-ui/themes";
import Navbar from "./components/navbar";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Theme
          appearance="dark"
          accentColor="gray"
          panelBackground="solid"
          radius="large"
        >
          <Container size="4">
            <Navbar />

            <Flex grow="1" align="center" justify="center">
              <main>{children}</main>
            </Flex>
          </Container>
        </Theme>
      </body>
    </html>
  );
}
